version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2024.01
      
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64/
      NVM_DIR: /home/circleci/.nvm
      ANDROID_HOME: /usr/lib/android-sdk
      PATH: $PATH:/usr/lib/android-sdk/tools/bin
    steps:
      # install nesessary dependencies holaa
      #- run: sudo apt update
      #- run: sudo apt install nodejs
      #- run: sudo apt install npm
      - run:
          name: install Main dependecies
          command: |
            apt update
            apt install nodejs
            apt install npm
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm --version
            nvm install 16
            nvm use 16
            npm install appium
            apt install openjdk-17-jdk
            echo -e "\e[31m ************ Install Android tools ************ \e[0m"
            apt-get -y install android-sdk
      - run:
          name: test sdk
          command: |
            sdkmanager
      #- run: npm install android-platform-tools
      #- run: sudo apt install openjdk-17-jdk
      #- run: npm install appium
      #- run: npm install android-platform-tools
      #- run: npm install appium-doctor
      # configuration of dependecies environment
      #- run: export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/bin/java
      #- run: export PATH=$PATH:$JAVA_HOME/bin
      #- run: sudo update-alternatives --config java
      
      # - run: sdkmanager
      # see correct dependeci installed
      - run: echo $JAVA_HOME
      - run: echo $ANDROID_HOME
      #- run: echo $PATH
      - run: java --version
      - run: node --version
      - run: npm --version
      - run: npx appium-doctor
runworkflows:
  version: 2
  scheduled-workflow-android:
    jobs:
    - build
