version: 2.1
jobs:
  build:
    macos:  # indicate that we are using the macOS executor
      xcode: 14.2.0
    environment:
      JAVA_HOME: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
      ANDROID_SDK_ROOT: /usr/local/Caskroom/android-sdk/4333796
    steps:
      - checkout
      - run: npm install -g react-native-cli
      - run: 
          name: Install Android sdk
          command: |
            brew install --cask homebrew/cask-versions/adoptopenjdk8
            brew install gradle
            brew install android-sdk
            brew install android-platform-tools
            brew install haxe
